### PR TITLE
Update HowwowKnyight

### PR DESCRIPTION
**Pull request by Ruttie2006**
Let's try this again.
@henpemaz

### CODE REVIEW

**Comment by henpemaz** [comment]
All fine! Thanks for fixing the mod and sorry for the trouble.
I think I don't have perms to merge this though so someone else will have to.

**Comment by Ruttie2006** [comment]
Yeah i'll wait for 56 to merge it. (or someone else)

**Comment by Ruttie2006** [comment]
Please tell me if adding another link like this works. 
If it does not, @SalehAce1 can you upload this zip to the site, it includes the beans.
https://github.com/Ruttie2006/BeansDefender/releases/download/Art/artmods.zip

**Comment by fifty-six** [comment]
I'm fine with the update for the howwow knight or whatever but art mods are angles, just add a new mod if anything

**Comment by Ruttie2006** [comment]
> I'm fine with the update for the howwow knight or whatever but art mods are angles, just add a new mod if anything

I added it as a new mod, is everything alright like this?

**Pull request merged**
