### PR TITLE
Add 9soulz_NG_Plus_ModPack

### PR DESCRIPTION
**Pull request by exsersewo**

### CODE REVIEW

**Comment by Ruttie2006** [comment]
not finished yet, don't merge for the time being

**Comment by exsersewo** [comment]
What do you mean?

**Comment by mandar1jn** [comment]
Hey. 1. The name of the mod can contain spaces. And 2. I don’t think you need to add Modding Api as a dependency since it has to be installed for mods to work

**Comment by exsersewo** [comment]
> Hey. 1. The name of the mod can contain spaces. And 2. I don’t think you need to add Modding Api as a dependency since it has to be installed for mods to work

1. Thanks for letting me know that.
2. This is mainly for consistencies sake as all the other mods reference the ModdingAPI as a dependency

**Comment by exsersewo** [comment]
Finished, currently testing.

**Comment by homothetyhk** [comment]
Closed due to inactivity.

**Pull request closed without merging**
